# Базовый образ для Airflow
FROM apache/airflow:2.9.2

USER root
# Установка OpenJDK 17
RUN apt-get update && apt-get install -y openjdk-17-jdk && apt-get clean

USER airflow
# Установка дополнительных пакетов, если требуется
RUN pip install apache-airflow-providers-apache-spark matplotlib seaborn clickhouse_driver pyspark